exports.blackList =
    [
        //TS1162:
        "conformance/types/objectTypeLiteral/methodSignatures/objectTypesWithOptionalProperties.ts",
        "compiler/spaceBeforeQuestionMarkInPropertyAssignment.ts",
        "compiler/objectTypeWithOptionalProperty1.ts",
        //TS1164: Computed property names are not allowed in enums. TS2452
        "conformance/parser/ecmascript6/ComputedPropertyNames/parserComputedPropertyName26.ts",
        "conformance/parser/ecmascript5/ComputedPropertyNames/parserES5ComputedPropertyName6.ts",
        "conformance/parser/ecmascript6/ComputedPropertyNames/parserComputedPropertyName34.ts",
        "compiler/literalsInComputedProperties1.ts",
        "conformance/parser/ecmascript6/ComputedPropertyNames/parserComputedPropertyName16.ts",
        //TS1166
        "compiler/computedPropertiesTransformedInOtherwiseNonTSClasses.ts",
        "conformance/parser/ecmascript6/ComputedPropertyNames/parserComputedPropertyName10.ts",
        "conformance/parser/ecmascript6/ComputedPropertyNames/parserComputedPropertyName29.ts",
        "compiler/indexSignatureWithInitializer.ts",
        //TS1184: Modifiers cannot appear here. TS1042, TS1030, TS1031
        "compiler/declareModifierOnImport1.ts",
        "compiler/exportAssignmentWithExportModifier.ts",
        "compiler/illegalModifiersOnClassElements.ts",
        "compiler/exportAssignmentWithDeclareAndExportModifiers.ts",
        "conformance/parser/ecmascript5/RegressionTests/parser618973.ts",
        "conformance/parser/ecmascript5/ErrorRecovery/parserModifierOnStatementInBlock3.ts",
        "conformance/parser/ecmascript5/ErrorRecovery/parserModifierOnStatementInBlock4.ts",
        "compiler/functionsWithModifiersInBlocks1.ts",
        "conformance/parser/ecmascript5/ErrorRecovery/parserModifierOnStatementInBlock1.ts",
        "conformance/async/es6/asyncEnum_es6.ts",
        "conformance/async/es5/asyncEnum_es5.ts",
        "compiler/exportAlreadySeen.ts",
        "compiler/exportAssignmentWithDeclareModifier.ts",
        "compiler/classExpressionPropertyModifiers.ts",
        "compiler/importDeclWithDeclareModifier.ts",
        //TS1095: A 'set' accessor cannot have a return type annotation.
        "conformance/parser/ecmascript5/Accessors/parserSetAccessorWithTypeAnnotation1.ts",
        //just ignoring this wrong elements
        "compiler/moduleElementsInWrongContext3.ts",
        "compiler/moduleElementsInWrongContext2.ts",
        "compiler/moduleElementsInWrongContext.ts",
        //TS2395: Individual declarations in merged declaration '{0}' must be all exported or all local.
        "compiler/duplicateSymbolsExportMatching.ts",
        "compiler/exportAssignmentImportMergeNoCrash.ts/user.ts",
        //TS1031: declare not allowed on methods
        "conformance/classes/propertyMemberDeclarations/derivedUninitializedPropertyDeclaration.ts",
        "conformance/parser/ecmascript5/MemberAccessorDeclarations/parserMemberAccessorDeclaration11.ts",
        "conformance/parser/ecmascript5/MemberFunctionDeclarations/parserMemberFunctionDeclaration5.ts",
        //wrong decorator
        "conformance/decorators/invalid/decoratorOnFunctionDeclaration.ts",
        "conformance/decorators/invalid/decoratorOnVar.ts",
        "conformance/decorators/class/accessor/decoratorOnClassAccessor7.ts",
        //should be bug with non-deleted unnecessary wrapper
        "compiler/collisionExportsRequireAndAmbientEnum.ts/collisionExportsRequireAndAmbientEnum_externalmodule.ts",
        "compiler/declareAlreadySeen.ts",
        "compiler/implicitAnyInAmbientDeclaration.ts",
        "compiler/enumAssignmentCompat3.ts",
        "compiler/collisionExportsRequireAndAmbientEnum.ts/collisionExportsRequireAndAmbientEnum_globalFile.ts",
        "compiler/specedNoStackBlown.ts",
        "conformance/ambient/ambientInsideNonAmbient.ts",
        "conformance/controlFlow/neverReturningFunctions1.ts",
        "conformance/controlFlow/assertionTypePredicates1.ts",
        "compiler/varBlock.ts",
        "compiler/collisionExportsRequireAndAmbientClass.ts/collisionExportsRequireAndAmbientClass_externalmodule.ts",
        //differences with constructor transformation
        "conformance/es6/Symbols/symbolProperty6.ts",
        "conformance/parser/ecmascript5/Symbols/parserES5SymbolProperty6.ts",
        "conformance/classes/members/privateNames/privateNameAndIndexSignature.ts",
        "conformance/parser/ecmascript6/Symbols/parserSymbolProperty6.ts",
        "conformance/classes/members/privateNames/privateNameCircularReference.ts",
        "compiler/protoAsIndexInIndexExpression.ts/protoAsIndexInIndexExpression_1.ts",
        "compiler/propertiesAndIndexersForNumericNames.ts",
        "conformance/classes/propertyMemberDeclarations/propertyNamedConstructor.ts",
        "conformance/es6/Symbols/symbolDeclarationEmit2.ts",
        "compiler/classIndexer5.ts",
        "compiler/unusedPrivateMembers.ts",
        "compiler/commentsInheritance.ts",
        "conformance/parser/ecmascript6/ComputedPropertyNames/parserComputedPropertyName25.ts",
        "conformance/parser/ecmascript5/ComputedPropertyNames/parserES5ComputedPropertyName10.ts",
        "compiler/sourceMapValidationClass.ts",
        "compiler/recursiveInheritance3.ts",
        "conformance/classes/members/classTypes/instancePropertyInClassType.ts",
        "compiler/unusedLocalsAndParametersDeferred.ts",
        "conformance/expressions/typeGuards/typeGuardOfFormThisMemberErrors.ts",
        "compiler/returnInConstructor1.ts",
        "compiler/varianceProblingAndZeroOrderIndexSignatureRelationsAlign.ts",
        "compiler/emitSuperCallBeforeEmitPropertyDeclarationAndParameterPropertyDeclaration1.ts",
        "conformance/classes/members/privateNames/privateNameDeclaration.ts",
        "compiler/emitSuperCallBeforeEmitPropertyDeclaration1.ts",
        "compiler/derivedClassConstructorWithExplicitReturns01.ts",
        "compiler/propertyOrdering.ts",
        "conformance/classes/propertyMemberDeclarations/initializerReferencingConstructorParameters.ts",
        "conformance/expressions/typeGuards/typeGuardOfFormThisMember.ts",
        "conformance/parser/ecmascript5/parserRealSource5.ts",
        "compiler/noImplicitAnyParametersInClass.ts",
        "compiler/declarationEmitPrivateNameCausesError.ts/file.ts",
        "conformance/classes/members/privateNames/privateNameFieldInitializer.ts",
        "compiler/classExpressions.ts",
        "compiler/abstractPropertyInConstructor.ts",
        "compiler/superElementAccess.ts",
        "compiler/emitSuperCallBeforeEmitPropertyDeclarationAndParameterPropertyDeclaration1ES6.ts",
        "compiler/moduleVisibilityTest2.ts",
        "compiler/es6ClassTest3.ts",
        "conformance/types/localTypes/localTypes3.ts",
        "compiler/functionsInClassExpressions.ts",
        "compiler/interfaceExtendsClassWithPrivate2.ts",
        "compiler/scopeCheckClassProperty.ts",
        "conformance/classes/members/privateNames/privateNamesAndDecorators.ts",
        "conformance/es6/for-ofStatements/for-of30.ts",
        "conformance/es6/classDeclaration/emitClassDeclarationWithConstructorInES6.ts",
        "conformance/statements/throwStatements/throwInEnclosingStatements.ts",
        "conformance/parser/ecmascript5/parserAstSpans1.ts",
        "conformance/classes/propertyMemberDeclarations/assignParameterPropertyToPropertyDeclarationESNext.ts",
        "compiler/readonlyMembers.ts",
        "conformance/classes/members/instanceAndStaticMembers/typeOfThisInInstanceMember2.ts",
        "conformance/types/localTypes/localTypes2.ts",
        "conformance/parser/ecmascript5/parserRealSource6.ts",
        "conformance/types/literal/literalTypesWidenInParameterPosition.ts",
        "conformance/types/namedTypes/optionalMethods.ts",
        "conformance/classes/members/privateNames/privateNamesAndGenericClasses-2.ts",
        "conformance/classes/members/privateNames/privateNameFieldUnaryMutation.ts",
        "compiler/superPropertyAccess.ts",
        "conformance/types/members/duplicatePropertyNames.ts",
        "compiler/collisionThisExpressionAndLocalVarInProperty.ts",
        "compiler/noCollisionThisExpressionAndLocalVarInProperty.ts",
        "compiler/classExtendsInterfaceThatExtendsClassWithPrivates1.ts",
        "compiler/moduleVisibilityTest1.ts",
        "compiler/privateVisibility.ts",
        "compiler/varianceProblingAndZeroOrderIndexSignatureRelationsAlign2.ts",
        "conformance/classes/constructorDeclarations/superCalls/derivedClassParameterProperties.ts",
        "compiler/lambdaPropSelf.ts",
        "compiler/thisBinding.ts",
        "compiler/abstractProperty.ts",
        "compiler/gettersAndSettersErrors.ts",
        "compiler/interfaceExtendsClassWithPrivate1.ts",
        "conformance/classes/members/instanceAndStaticMembers/typeOfThisInInstanceMember.ts",
        "compiler/collisionSuperAndParameter.ts",
        "conformance/classes/members/classTypes/instancePropertiesInheritedIntoClassType.ts",
        "compiler/invalidThisEmitInContextualObjectLiteral.ts",
        "compiler/emitSuperCallBeforeEmitPropertyDeclaration1ES6.ts",
        "compiler/noCrashOnThisTypeUsage.ts",
        //differences with object/array binding patterns assignments transformation
        "compiler/downlevelLetConst13.ts",
        "compiler/destructuringInVariableDeclarations7.ts",
        "compiler/destructuringInVariableDeclarations5.ts",
        "compiler/destructuringInVariableDeclarations3.ts",
        "compiler/destructuringInVariableDeclarations1.ts",
        "compiler/declarationEmitDestructuringObjectLiteralPattern2.ts",
        "compiler/exportObjectRest.ts",
        "compiler/systemModule8.ts",
        "compiler/bindingPatternOmittedExpressionNesting.ts",
        "compiler/declarationEmitDestructuringObjectLiteralPattern.ts",
        "conformance/classes/propertyMemberDeclarations/defineProperty.ts",
        "compiler/systemModule13.ts",
        "compiler/superCallInNonStaticMethod.ts",//needs detailed observation
        "compiler/recursiveSpecializationOfSignatures.ts",
        "conformance/es6/destructuring/declarationsAndAssignments.ts",
        "compiler/declarationEmitRetainsJsdocyComments.ts",
        "compiler/declarationEmitDestructuringPrivacyError.ts",
        "compiler/destructuringAssignmentWithExportedName.ts",
        "compiler/declarationEmitPrivateSymbolCausesVarDeclarationEmit2.ts/c.ts",
        "compiler/declarationEmitPrivateSymbolCausesVarDeclarationEmit2.ts/b.ts",
        "compiler/declarationEmitDestructuringArrayPattern3.ts",
        "conformance/classes/propertyMemberDeclarations/instanceMemberWithComputedPropertyName.ts",
        //wrong arg in import statement
        "conformance/dynamicImport/importCallExpressionGrammarError.ts",
        //unnesessary namespaces renaming?
        "conformance/externalModules/duplicateExportAssignments.ts/foo3.ts",
        "compiler/collisionCodeGenModuleWithConstructorChildren.ts",
        "compiler/mergedModuleDeclarationCodeGen4.ts",
        "compiler/collisionCodeGenModuleWithModuleReopening.ts",
        "compiler/recursiveCloduleReference.ts",
        "compiler/collisionCodeGenModuleWithFunctionChildren.ts",
        "compiler/isDeclarationVisibleNodeKinds.ts",
        "compiler/importAndVariableDeclarationConflict4.ts",
        "compiler/moduleSharesNameWithImportDeclarationInsideIt6.ts",
        "compiler/importAndVariableDeclarationConflict2.ts",
        "compiler/declarationEmitImportInExportAssignmentModule.ts",
        "compiler/moduleSharesNameWithImportDeclarationInsideIt5.ts",
        "compiler/cloduleWithRecursiveReference.ts",
        "compiler/moduleSharesNameWithImportDeclarationInsideIt4.ts",
        "conformance/internalModules/exportDeclarations/ModuleWithExportedAndNonExportedClasses.ts",
        "conformance/decorators/class/decoratedClassExportsSystem2.ts/a.ts",
        "conformance/internalModules/codeGeneration/nameCollision.ts",
        "compiler/collisionCodeGenModuleWithMethodChildren.ts",
        "compiler/importAndVariableDeclarationConflict3.ts",
        "conformance/decorators/class/decoratedClassExportsCommonJS2.ts/a.ts",
        "compiler/nameCollisionWithBlockScopedVariable1.ts",
        "compiler/collisionCodeGenModuleWithMemberVariable.ts",
        "compiler/collisionCodeGenModuleWithPrivateMember.ts",
        "compiler/collisionCodeGenModuleWithMemberClassConflict.ts",
        "compiler/privacyImportParseErrors.ts",
        "compiler/moduleSharesNameWithImportDeclarationInsideIt.ts",
        "compiler/importAndVariableDeclarationConflict1.ts",
        "compiler/importedModuleAddToGlobal.ts",
        "compiler/mergedModuleDeclarationCodeGen5.ts",
        "compiler/moduledecl.ts",
        "compiler/mergedModuleDeclarationCodeGen.ts",
        "compiler/collisionCodeGenModuleWithAccessorChildren.ts",
        "compiler/mergedModuleDeclarationCodeGen2.ts",
        "compiler/thisInModuleFunction1.ts",
        "compiler/mergedModuleDeclarationCodeGen3.ts",
        "compiler/recursiveClassReferenceTest.ts",
        "compiler/declFileImportChainInExportAssignment.ts",
        "compiler/collisionCodeGenModuleWithModuleChildren.ts",
        "compiler/moduleSharesNameWithImportDeclarationInsideIt3.ts",
        "compiler/privacyGloImportParseErrors.ts",
        //TS1094
        "conformance/parser/ecmascript5/Accessors/parserSetAccessorWithTypeParameters1.ts",
        "conformance/parser/ecmascript5/Accessors/parserGetAccessorWithTypeParameters1.ts",
        //TS1248
        "compiler/constInClassExpression.ts",
        //could be quite tricky to delete wrappers with only unused imports
        "projects/NestedLocalModule-SimpleCase/test1.ts",
        "compiler/internalImportInstantiatedModuleMergedWithClassNotReferencingInstanceNoConflict.ts",
        "compiler/internalAliasWithDottedNameEmit.ts",
        "conformance/internalModules/codeGeneration/importStatements.ts",
        "conformance/internalModules/codeGeneration/importStatementsInterfaces.ts",
        "compiler/dottedModuleName2.ts",
        "compiler/unusedImports10.ts",
        "conformance/decorators/invalid/decoratorOnImportEquals1.ts",
        "compiler/qualifiedName_ImportDeclarations-entity-names-referencing-a-var.ts",
        "compiler/importInTypePosition.ts",
        "compiler/internalImportUnInstantiatedModuleMergedWithClassNotReferencingInstanceNoConflict.ts",
        "compiler/moduleCrashBug1.ts",
        //no diffs
        "conformance/types/typeRelationships/comparable/optionalProperties02.ts",
        "compiler/arrowFunctionWithObjectLiteralBody2.ts",
        "compiler/arrowFunctionWithObjectLiteralBody4.ts",
        "conformance/parser/ecmascript5/RegularExpressions/parseRegularExpressionMixedWithComments.ts",
        "conformance/salsa/typeFromPropertyAssignment31.ts",
        "conformance/types/rest/restTuplesFromContextualTypes.ts",
        "compiler/quotedPropertyName1.ts",
        "compiler/constDeclarations2.ts",
        "conformance/externalModules/asiPreventsParsingAsAmbientExternalModule02.ts",
        "conformance/externalModules/asiPreventsParsingAsAmbientExternalModule01.ts",
        "conformance/es6/templates/templateStringTermination1.ts",
        "conformance/parser/ecmascript5/parser15.4.4.14-9-2.ts",
        "conformance/es7/exponentiationOperator/exponentiationOperatorWithInvalidSimpleUnaryExpressionOperands.ts",
        "compiler/functionOverloads1.ts",
        "compiler/bigintWithoutLib.ts",
        "compiler/bigintWithLib.ts",
        "conformance/es6/templates/templateStringTermination2.ts",
        "fourslash/codeFixClassImplementInterfaceEmptyTypeLiteral.ts",
        "conformance/es6/templates/templateStringTermination3.ts",
        "fourslash/codeFixClassImplementInterfaceSomePropertiesPresent.ts",
        "conformance/es6/templates/templateStringTermination4.ts",
        "conformance/es6/templates/templateStringTermination5.ts",
        "fourslash/syntacticClassificationsTripleSlash11.ts",
        "fourslash/syntacticClassificationsTripleSlash3.ts",
        "fourslash/syntacticClassificationsTripleSlash16.ts",
        "fourslash/syntacticClassificationsTripleSlash15.ts",
        "fourslash/syntacticClassifications1.ts",
        "fourslash/syntacticClassificationsTripleSlash8.ts",
        "fourslash/shims-pp/getSyntacticClassifications.ts",
        "fourslash/syntacticClassificationsTripleSlash1.ts",
        "fourslash/syntacticClassificationsTripleSlash10.ts",
        "fourslash/syntacticClassificationsTripleSlash5.ts",
        "fourslash/syntacticClassificationsTripleSlash9.ts",
        "fourslash/syntacticClassificationsTripleSlash13.ts",
        "fourslash/shims/getSyntacticClassifications.ts",
        "fourslash/syntacticClassificationsTripleSlash6.ts",
        "fourslash/syntacticClassificationsTripleSlash2.ts",
        "fourslash/syntacticClassificationsTripleSlash12.ts",
        "fourslash/syntacticClassificationsTripleSlash7.ts",
        "compiler/useStrictLikePrologueString01.ts",//differences ignored
        "compiler/es6ExportClauseWithAssignmentInEs5.ts/server.ts",//???????????
        //differences with alias export declarations
        "conformance/es6/modules/exportsAndImports4-es6.ts/t3.ts",
        "conformance/es6/modules/exportsAndImports4-amd.ts/t3.ts",
        "conformance/es6/modules/exportsAndImports4.ts/t2.ts",
        "conformance/es6/modules/exportsAndImports4-amd.ts/t2.ts",
        "compiler/systemModule9.ts",
        "conformance/es6/modules/exportsAndImports4.ts/t3.ts",
        "conformance/es6/modules/exportsAndImports4-es6.ts/t2.ts",
        //differences in module namings
        "compiler/isolatedModulesReExportType.ts/user.ts",
        "compiler/unusedImports_entireImportDeclaration.ts/b.ts",
        "conformance/externalModules/typeOnly/chained.ts/b.ts",
        "compiler/es6ImportDefaultBindingFollowedWithNamedImportWithExport.ts/client.ts",
        "compiler/es6ImportDefaultBindingFollowedWithNamedImportDts.ts/client.ts",
        "compiler/es6ImportDefaultBindingFollowedWithNamedImportInEs5.ts/es6ImportDefaultBindingFollowedWithNamedImportInEs5_1.ts",
        "compiler/es6ImportDefaultBindingFollowedWithNamedImport.ts/es6ImportDefaultBindingFollowedWithNamedImport_1.ts",
        "compiler/es6ExportEqualsInterop.ts/main.ts",
        //should be bug in Typescript with non-deleted unnecessary or unused import
        "conformance/scanner/ecmascript5/scannerImportDeclaration1.ts",
        "conformance/parser/ecmascript5/parserImportDeclaration1.ts",
        "conformance/internalModules/importDeclarations/importAliasIdentifiers.ts",
        "conformance/internalModules/importDeclarations/invalidImportAliasIdentifiers.ts",
        "compiler/duplicateVarAndImport2.ts",
        "compiler/jsdocInTypeScript.ts",
        "compiler/collisionThisExpressionAndAliasInGlobal.ts",
        "compiler/moduleAliasInterface.ts",
        "conformance/externalModules/commonJSImportNotAsPrimaryExpression.ts/foo_1.ts",
        "conformance/externalModules/amdImportNotAsPrimaryExpression.ts/foo_1.ts",
        "compiler/aliasBug.ts",
        //TS1380: import type only. TS1361:
        "conformance/externalModules/typeOnly/exportDefault.ts/g.ts",
        "conformance/externalModules/typeOnly/importEquals3.ts/b.ts",
        "conformance/externalModules/typeOnly/importClause_default.ts/b.ts",
        "conformance/externalModules/typeOnly/filterNamespace_import.ts/a.ts",
        "conformance/externalModules/typeOnly/importEquals1.ts/g.ts",
        //TS2309: An export assignment cannot be used in a module with other exported elements.
        "conformance/parser/ecmascript5/ExportAssignments/parserExportAssignment8.ts",
        "compiler/ExportAssignment7.ts",
        "compiler/ExportAssignment8.ts",
        "compiler/es6ExportEquals.ts",
        "compiler/es5ExportEquals.ts",
        "compiler/exportAssignmentWithExports.ts",
        "conformance/parser/ecmascript5/ExportAssignments/parserExportAssignment7.ts",
        //TODO: check this! there shouldn't be reference, could be tricky in realization
        "conformance/enums/enumMerging.ts",
        "compiler/mergedDeclarations4.ts",
        "compiler/emitMemberAccessExpression.ts/emitMemberAccessExpression_file2.ts",
        //TS1147: Import declarations in a namespace cannot reference a module.
        "projects/privacyCheck-InsideModule/test.ts",
        "projects/privacyCheck-InsideModule/testGlo.ts",
        "projects/privacyCheck-ImportInParent/test.ts",
        "projects/NestedLocalModule-WithRecursiveTypecheck/test1.ts",
        "compiler/importInsideModule.ts/importInsideModule_file2.ts",
        "projects/ext-int-ext/internal2.ts",
        "projects/NestedLocalModule-WithRecursiveTypecheck/test2.ts",
        //TS2440: Import declaration conflicts with local declaration of '{0}'.
        "compiler/importedEnumMemberMergedWithExportedAliasIsError.ts/alias.ts",
        "compiler/namespaceMergedWithImportAliasNoCrash.ts/file2.ts",
        //TS2323:
        "compiler/declarationFileNoCrashOnExtraExportModifier.ts/input.ts",
        //TS1005:
        "compiler/accessorWithoutBody1.ts",
        "compiler/accessorWithoutBody2.ts",
        "compiler/abstractPropertyNegative.ts",
        //TS1092,TS1093
        "conformance/parser/ecmascript5/ConstructorDeclarations/parserConstructorDeclaration10.ts",
        "conformance/parser/ecmascript5/ConstructorDeclarations/parserConstructorDeclaration9.ts",
        //TS1211:
        "compiler/exportClassWithoutName.ts",
        //TS1319
        "compiler/exportDefaultFunctionInNamespace.ts",
        "compiler/exportDefaultClassInNamespace.ts",
        "conformance/parser/ecmascript5/ExportAssignments/parserExportAssignment9.ts",
        //unterminated nextline chars
        "compiler/fileWithNextLine2.ts",
        "compiler/fileWithNextLine3.ts",
        "compiler/sourceMap-LineBreaks.ts",
        //differences in computed properties transformation
        "conformance/es6/Symbols/symbolProperty7.ts",
        "compiler/decoratorsOnComputedProperties.ts",
        "conformance/parser/ecmascript6/ComputedPropertyNames/parserComputedPropertyName28.ts",
        "conformance/externalModules/typeOnly/computedPropertyName.ts/component.ts",
        "compiler/variableDeclarationDeclarationEmitUniqueSymbolPartialStatement.ts",
        //TS2332
        "compiler/this_inside-enum-should-not-be-allowed.ts",
        //TODO: non-merged declarations
        "compiler/enumGenericTypeClash.ts",
        "compiler/constEnumErrors.ts",
        "compiler/augmentedTypesClass.ts",
        "compiler/augmentedTypesClass2.ts",
        "compiler/augmentedTypesFunction.ts",
        //TS2334:
        "compiler/augmentedTypesModules2.ts",
        "compiler/augmentedTypesModules.ts",
        "conformance/internalModules/DeclarationMerging/ModuleAndFunctionWithSameNameAndCommonRoot.ts/simple.ts",
        //TODO: numeric separators
        "conformance/salsa/typeFromPropertyAssignment29.ts",
        "conformance/parser/ecmascriptnext/numericSeparators/parser.numericSeparators.hex.ts",
        "conformance/parser/ecmascriptnext/numericSeparators/parser.numericSeparators.binary.ts",
        "conformance/parser/ecmascriptnext/numericSeparators/parser.numericSeparators.octal.ts",
        "conformance/salsa/typeFromPropertyAssignment29.ts",
        "conformance/parser/ecmascriptnext/numericSeparators/parser.numericSeparators.decimal.ts",
        "compiler/bigIntWithTargetES3.ts", //actually bigint
        //TODO: trailing slashes in imports?
        "compiler/importWithTrailingSlash.ts/a/test.ts",
        "compiler/importWithTrailingSlash.ts/a/b/test.ts",
        "compiler/exportStarNotElided.ts/data1.ts",
        //TS1315:
        "conformance/externalModules/umd-errors.ts/err5.ts",
        //strange case with quoted constructors
        "conformance/classes/constructorDeclarations/quotedConstructors.ts",
        //TODO: empty object/array bindging patterns
        "compiler/exportEmptyObjectBindingPattern.ts",
        "compiler/exportEmptyArrayBindingPattern.ts",
        //TODO: may be bug with wrong import
        "compiler/exportImportCanSubstituteConstEnumForValue.ts",
        //unneccessary import chain:  difficult to solve
        "compiler/importedAliasesInTypePositions.ts/file2.ts",
        //TODO: unicode in enums
        "compiler/enumWithUnicodeEscape1.ts",
        //TS1358:
        "conformance/expressions/optionalChaining/taggedTemplateChain/taggedTemplateChain.ts",
        //TODO: decorator references??
        "compiler/decoratorReferences.ts",
        //just shadow import
        "compiler/noCrashOnImportShadowing.ts/a.ts",
        //strange case
        "compiler/parseGenericArrowRatherThanLeftShift.ts",
        "compiler/reExportUndefined1.ts/a.ts",
        //Object.defineProperty instead of exports
        "conformance/es6/modules/exportsAndImports3-amd.ts/t1.ts",
        "conformance/es6/modules/exportsAndImports3-es6.ts/t1.ts",
        "conformance/es6/modules/exportsAndImports3.ts/t1.ts",
        //tests with typescript errors generated as is
        "compiler/arrowFunctionErrorSpan.ts",
        "compiler/classHeritageWithTrailingSeparator.ts",
        "compiler/constructorArgsErrors5.ts",
        "conformance/es6/arrowFunction/disallowLineTerminatorBeforeArrow.ts",
        "conformance/es7/trailingCommasInFunctionParametersAndArguments.ts",
        "conformance/parser/ecmascript5/ErrorRecovery/ExtendsOrImplementsClauses/parserErrorRecovery_ExtendsOrImplementsClause2.ts",
        "conformance/parser/ecmascript5/ErrorRecovery/ExtendsOrImplementsClauses/parserErrorRecovery_ExtendsOrImplementsClause5.ts",
        "conformance/parser/ecmascript5/VariableDeclarations/parserVariableDeclaration10.ts",
        "conformance/parser/ecmascript5/VariableDeclarations/parserVariableDeclaration5.ts",
        "conformance/parser/ecmascript5/ErrorRecovery/VariableLists/parserErrorRecovery_VariableList1.ts",
        //test fail in typescript transpiler
        "compiler/binderBinaryExpressionStress.ts",
        "compiler/noCrashOnMixin.ts",
        //rare case when diff regexp working wrong
        "unittests/matchFiles.ts"
    ];