exports.blackList =
    [
        //TS1162:
        "conformance/types/objectTypeLiteral/methodSignatures/objectTypesWithOptionalPropertiesJs.js",
        "compiler/spaceBeforeQuestionMarkInPropertyAssignmentJs.js",
        "compiler/objectTypeWithOptionalProperty1Js.js",
        //TS1164: Computed property names are not allowed in enums.
        "conformance/parser/ecmascript5/ComputedPropertyNames/parserES5ComputedPropertyName6Js.js",
        "conformance/parser/ecmascript6/ComputedPropertyNames/parserComputedPropertyName34Js.js",
        //TS1166
        "compiler/computedPropertiesTransformedInOtherwiseNonTSClassesJs.js",
        "conformance/parser/ecmascript6/ComputedPropertyNames/parserComputedPropertyName10Js.js",
        "conformance/parser/ecmascript6/ComputedPropertyNames/parserComputedPropertyName29Js.js",
        "compiler/indexSignatureWithInitializerJs.js",
        //TS1184: Modifiers cannot appear here. TS1042, TS1030, TS1031
        "compiler/exportAssignmentWithExportModifierJs.js",
        "compiler/illegalModifiersOnClassElementsJs.js",
        "compiler/exportAssignmentWithDeclareAndExportModifiersJs.js",
        "conformance/parser/ecmascript5/RegressionTests/parser618973Js.js",
        "conformance/parser/ecmascript5/ErrorRecovery/parserModifierOnStatementInBlock3Js.js",
        "conformance/parser/ecmascript5/ErrorRecovery/parserModifierOnStatementInBlock4Js.js",
        "compiler/functionsWithModifiersInBlocks1Js.js",
        "conformance/parser/ecmascript5/ErrorRecovery/parserModifierOnStatementInBlock1Js.js",
        "conformance/async/es6/asyncEnum_es6Js.js",
        "conformance/async/es5/asyncEnum_es5Js.js",
        "compiler/exportAlreadySeenJs.js",
        "compiler/exportAssignmentWithDeclareModifierJs.js",
        "compiler/classExpressionPropertyModifiersJs.js",
        "compiler/importDeclWithDeclareModifierJs.js",
        //TS1095: A 'set' accessor cannot have a return type annotation.
        "conformance/parser/ecmascript5/Accessors/parserSetAccessorWithTypeAnnotation1Js.js",
        //just ignoring this wrong elements
        "compiler/moduleElementsInWrongContext3Js.js",
        "compiler/moduleElementsInWrongContext2Js.js",
        "compiler/moduleElementsInWrongContextJs.js",
        //TS2395: Individual declarations in merged declaration '{0}' must be all exported or all local.
        "compiler/duplicateSymbolsExportMatchingJs.js",
        "compiler/exportAssignmentImportMergeNoCrash.ts/userJs.js",
        //TS1031: declare not allowed on methods
        "conformance/classes/propertyMemberDeclarations/derivedUninitializedPropertyDeclarationJs.js",
        "conformance/parser/ecmascript5/MemberAccessorDeclarations/parserMemberAccessorDeclaration11Js.js",
        "conformance/parser/ecmascript5/MemberFunctionDeclarations/parserMemberFunctionDeclaration5Js.js",
        //wrong decorator
        "conformance/decorators/invalid/decoratorOnFunctionDeclarationJs.js",
        "conformance/decorators/invalid/decoratorOnVarJs.js",
        "conformance/decorators/class/accessor/decoratorOnClassAccessor7Js.js",
        //should be bug with non-deleted unnecessary wrapper
        "compiler/collisionExportsRequireAndAmbientEnum.ts/collisionExportsRequireAndAmbientEnum_externalmoduleJs.js",
        "compiler/declareAlreadySeenJs.js",
        "compiler/implicitAnyInAmbientDeclarationJs.js",
        "compiler/enumAssignmentCompat3Js.js",
        "compiler/collisionExportsRequireAndAmbientEnum.ts/collisionExportsRequireAndAmbientEnum_globalFileJs.js",
        "compiler/specedNoStackBlownJs.js",
        "conformance/ambient/ambientInsideNonAmbientJs.js",
        "conformance/controlFlow/neverReturningFunctions1Js.js",
        "conformance/controlFlow/assertionTypePredicates1Js.js",
        "compiler/varBlockJs.js",
        "compiler/collisionExportsRequireAndAmbientClass.ts/collisionExportsRequireAndAmbientClass_externalmoduleJs.js",
        //differences with constructor transformation
        "compiler/classIndexer5Js.js",
        "compiler/unusedPrivateMembersJs.js",
        "compiler/commentsInheritanceJs.js",
        "conformance/parser/ecmascript6/ComputedPropertyNames/parserComputedPropertyName25Js.js",
        "conformance/parser/ecmascript5/ComputedPropertyNames/parserES5ComputedPropertyName10Js.js",
        "compiler/sourceMapValidationClassJs.js",
        "compiler/recursiveInheritance3Js.js",
        "conformance/classes/members/classTypes/instancePropertyInClassTypeJs.js",
        "compiler/unusedLocalsAndParametersDeferredJs.js",
        "conformance/expressions/typeGuards/typeGuardOfFormThisMemberErrorsJs.js",
        "compiler/returnInConstructor1Js.js",
        "compiler/varianceProblingAndZeroOrderIndexSignatureRelationsAlignJs.js",
        "compiler/emitSuperCallBeforeEmitPropertyDeclarationAndParameterPropertyDeclaration1Js.js",
        "conformance/classes/members/privateNames/privateNameDeclarationJs.js",
        "compiler/emitSuperCallBeforeEmitPropertyDeclaration1Js.js",
        "compiler/derivedClassConstructorWithExplicitReturns01Js.js",
        "compiler/propertyOrderingJs.js",
        "conformance/classes/propertyMemberDeclarations/initializerReferencingConstructorParametersJs.js",
        "conformance/expressions/typeGuards/typeGuardOfFormThisMemberJs.js",
        "conformance/parser/ecmascript5/parserRealSource5Js.js",
        "compiler/noImplicitAnyParametersInClassJs.js",
        "compiler/declarationEmitPrivateNameCausesError.ts/fileJs.js",
        "conformance/classes/members/privateNames/privateNameFieldInitializerJs.js",
        "compiler/classExpressionsJs.js",
        "compiler/abstractPropertyInConstructorJs.js",
        "compiler/superElementAccessJs.js",
        "compiler/emitSuperCallBeforeEmitPropertyDeclarationAndParameterPropertyDeclaration1ES6Js.js",
        "compiler/moduleVisibilityTest2Js.js",
        "compiler/es6ClassTest3Js.js",
        "conformance/types/localTypes/localTypes3Js.js",
        "compiler/functionsInClassExpressionsJs.js",
        "compiler/interfaceExtendsClassWithPrivate2Js.js",
        "compiler/scopeCheckClassPropertyJs.js",
        "conformance/classes/members/privateNames/privateNamesAndDecoratorsJs.js",
        "conformance/es6/for-ofStatements/for-of30Js.js",
        "conformance/es6/classDeclaration/emitClassDeclarationWithConstructorInES6Js.js",
        "conformance/statements/throwStatements/throwInEnclosingStatementsJs.js",
        "conformance/parser/ecmascript5/parserAstSpans1Js.js",
        "conformance/classes/propertyMemberDeclarations/assignParameterPropertyToPropertyDeclarationESNextJs.js",
        "compiler/readonlyMembersJs.js",
        "conformance/classes/members/instanceAndStaticMembers/typeOfThisInInstanceMember2Js.js",
        "conformance/types/localTypes/localTypes2Js.js",
        "conformance/parser/ecmascript5/parserRealSource6Js.js",
        "conformance/types/literal/literalTypesWidenInParameterPositionJs.js",
        "conformance/types/namedTypes/optionalMethodsJs.js",
        "conformance/classes/members/privateNames/privateNamesAndGenericClasses-2Js.js",
        "conformance/classes/members/privateNames/privateNameFieldUnaryMutationJs.js",
        "compiler/superPropertyAccessJs.js",
        "conformance/types/members/duplicatePropertyNamesJs.js",
        "compiler/collisionThisExpressionAndLocalVarInPropertyJs.js",
        "compiler/noCollisionThisExpressionAndLocalVarInPropertyJs.js",
        "compiler/classExtendsInterfaceThatExtendsClassWithPrivates1Js.js",
        "compiler/moduleVisibilityTest1Js.js",
        "compiler/privateVisibilityJs.js",
        "compiler/varianceProblingAndZeroOrderIndexSignatureRelationsAlign2Js.js",
        "conformance/classes/constructorDeclarations/superCalls/derivedClassParameterPropertiesJs.js",
        "compiler/lambdaPropSelfJs.js",
        "compiler/thisBindingJs.js",
        "compiler/abstractPropertyJs.js",
        "compiler/gettersAndSettersErrorsJs.js",
        "compiler/interfaceExtendsClassWithPrivate1Js.js",
        "conformance/classes/members/instanceAndStaticMembers/typeOfThisInInstanceMemberJs.js",
        "compiler/collisionSuperAndParameterJs.js",
        "conformance/classes/members/classTypes/instancePropertiesInheritedIntoClassTypeJs.js",
        "compiler/invalidThisEmitInContextualObjectLiteralJs.js",
        "compiler/emitSuperCallBeforeEmitPropertyDeclaration1ES6Js.js",
        "compiler/noCrashOnThisTypeUsageJs.js",
        //differences with object/array binding patterns assignments transformation
        "compiler/downlevelLetConst13Js.js",
        "compiler/destructuringInVariableDeclarations7Js.js",
        "compiler/destructuringInVariableDeclarations5Js.js",
        "compiler/destructuringInVariableDeclarations3Js.js",
        "compiler/destructuringInVariableDeclarations1Js.js",
        "compiler/declarationEmitDestructuringObjectLiteralPattern2Js.js",
        "compiler/exportObjectRestJs.js",
        "compiler/systemModule8Js.js",
        "compiler/bindingPatternOmittedExpressionNestingJs.js",
        "compiler/declarationEmitDestructuringObjectLiteralPatternJs.js",
        "conformance/classes/propertyMemberDeclarations/definePropertyJs.js",
        "compiler/systemModule13Js.js",
        "compiler/superCallInNonStaticMethodJs.js",//needs detailed observation
        "compiler/recursiveSpecializationOfSignaturesJs.js",
        "conformance/es6/destructuring/declarationsAndAssignmentsJs.js",
        "compiler/declarationEmitRetainsJsdocyCommentsJs.js",
        "compiler/declarationEmitDestructuringPrivacyErrorJs.js",
        "compiler/destructuringAssignmentWithExportedNameJs.js",
        "compiler/declarationEmitPrivateSymbolCausesVarDeclarationEmit2.ts/cJs.js",
        "compiler/declarationEmitPrivateSymbolCausesVarDeclarationEmit2.ts/bJs.js",
        "compiler/declarationEmitDestructuringArrayPattern3Js.js",
        "conformance/classes/propertyMemberDeclarations/instanceMemberWithComputedPropertyNameJs.js",
        //wrong arg in import statement
        "conformance/dynamicImport/importCallExpressionGrammarErrorJs.js",
        //unnesessary namespaces renaming?
        "conformance/externalModules/duplicateExportAssignments.ts/foo3Js.js",
        "compiler/collisionCodeGenModuleWithConstructorChildrenJs.js",
        "compiler/mergedModuleDeclarationCodeGen4Js.js",
        "compiler/collisionCodeGenModuleWithModuleReopeningJs.js",
        "compiler/recursiveCloduleReferenceJs.js",
        "compiler/collisionCodeGenModuleWithFunctionChildrenJs.js",
        "compiler/isDeclarationVisibleNodeKindsJs.js",
        "compiler/importAndVariableDeclarationConflict4Js.js",
        "compiler/moduleSharesNameWithImportDeclarationInsideIt6Js.js",
        "compiler/importAndVariableDeclarationConflict2Js.js",
        "compiler/declarationEmitImportInExportAssignmentModuleJs.js",
        "compiler/moduleSharesNameWithImportDeclarationInsideIt5Js.js",
        "compiler/cloduleWithRecursiveReferenceJs.js",
        "compiler/moduleSharesNameWithImportDeclarationInsideIt4Js.js",
        "conformance/internalModules/exportDeclarations/ModuleWithExportedAndNonExportedClassesJs.js",
        "conformance/decorators/class/decoratedClassExportsSystem2.ts/aJs.js",
        "conformance/internalModules/codeGeneration/nameCollisionJs.js",
        "compiler/collisionCodeGenModuleWithMethodChildrenJs.js",
        "compiler/importAndVariableDeclarationConflict3Js.js",
        "conformance/decorators/class/decoratedClassExportsCommonJS2.ts/aJs.js",
        "compiler/nameCollisionWithBlockScopedVariable1Js.js",
        "compiler/collisionCodeGenModuleWithMemberVariableJs.js",
        "compiler/collisionCodeGenModuleWithPrivateMemberJs.js",
        "compiler/collisionCodeGenModuleWithMemberClassConflictJs.js",
        "compiler/privacyImportParseErrorsJs.js",
        "compiler/moduleSharesNameWithImportDeclarationInsideItJs.js",
        "compiler/importAndVariableDeclarationConflict1Js.js",
        "compiler/importedModuleAddToGlobalJs.js",
        "compiler/mergedModuleDeclarationCodeGen5Js.js",
        "compiler/moduledeclJs.js",
        "compiler/mergedModuleDeclarationCodeGenJs.js",
        "compiler/collisionCodeGenModuleWithAccessorChildrenJs.js",
        "compiler/mergedModuleDeclarationCodeGen2Js.js",
        "compiler/thisInModuleFunction1Js.js",
        "compiler/mergedModuleDeclarationCodeGen3Js.js",
        "compiler/recursiveClassReferenceTestJs.js",
        "compiler/declFileImportChainInExportAssignmentJs.js",
        "compiler/collisionCodeGenModuleWithModuleChildrenJs.js",
        "compiler/moduleSharesNameWithImportDeclarationInsideIt3Js.js",
        "compiler/privacyGloImportParseErrorsJs.js",
        //TS1094
        "conformance/parser/ecmascript5/Accessors/parserSetAccessorWithTypeParameters1Js.js",
        "conformance/parser/ecmascript5/Accessors/parserGetAccessorWithTypeParameters1Js.js",
        //TS1248
        "compiler/constInClassExpressionJs.js",
        //could be quite tricky to delete wrappers with only unused imports
        "projects/NestedLocalModule-SimpleCase/test1Js.js",
        "compiler/internalImportInstantiatedModuleMergedWithClassNotReferencingInstanceNoConflictJs.js",
        "compiler/internalAliasWithDottedNameEmitJs.js",
        "conformance/internalModules/codeGeneration/importStatementsJs.js",
        "conformance/internalModules/codeGeneration/importStatementsInterfacesJs.js",
        "compiler/dottedModuleName2Js.js",
        "compiler/unusedImports10Js.js",
        "conformance/decorators/invalid/decoratorOnImportEquals1Js.js",
        "compiler/qualifiedName_ImportDeclarations-entity-names-referencing-a-varJs.js",
        "compiler/importInTypePositionJs.js",
        "compiler/internalImportUnInstantiatedModuleMergedWithClassNotReferencingInstanceNoConflictJs.js",
        "compiler/moduleCrashBug1Js.js",
        //no diffs
        "conformance/es6/templates/templateStringTermination1Js.js",
        "conformance/parser/ecmascript5/parser15.4.4.14-9-2Js.js",
        "conformance/es7/exponentiationOperator/exponentiationOperatorWithInvalidSimpleUnaryExpressionOperandsJs.js",
        "compiler/functionOverloads1Js.js",
        "compiler/bigintWithoutLibJs.js",
        "compiler/bigintWithLibJs.js",
        "conformance/es6/templates/templateStringTermination2Js.js",
        "fourslash/codeFixClassImplementInterfaceEmptyTypeLiteralJs.js",
        "conformance/es6/templates/templateStringTermination3Js.js",
        "fourslash/codeFixClassImplementInterfaceSomePropertiesPresentJs.js",
        "conformance/es6/templates/templateStringTermination4Js.js",
        "conformance/es6/templates/templateStringTermination5Js.js",
        "fourslash/syntacticClassificationsTripleSlash11Js.js",
        "fourslash/syntacticClassificationsTripleSlash3Js.js",
        "fourslash/syntacticClassificationsTripleSlash16Js.js",
        "fourslash/syntacticClassificationsTripleSlash15Js.js",
        "fourslash/syntacticClassifications1Js.js",
        "fourslash/syntacticClassificationsTripleSlash8Js.js",
        "fourslash/shims-pp/getSyntacticClassificationsJs.js",
        "fourslash/syntacticClassificationsTripleSlash1Js.js",
        "fourslash/syntacticClassificationsTripleSlash10Js.js",
        "fourslash/syntacticClassificationsTripleSlash5Js.js",
        "fourslash/syntacticClassificationsTripleSlash9Js.js",
        "fourslash/syntacticClassificationsTripleSlash13Js.js",
        "fourslash/shims/getSyntacticClassificationsJs.js",
        "fourslash/syntacticClassificationsTripleSlash6Js.js",
        "fourslash/syntacticClassificationsTripleSlash2Js.js",
        "fourslash/syntacticClassificationsTripleSlash12Js.js",
        "fourslash/syntacticClassificationsTripleSlash7Js.js",
        "compiler/useStrictLikePrologueString01Js.js",//differences ignored
        "compiler/es6ExportClauseWithAssignmentInEs5.ts/serverJs.js",//???????????
        //differences with alias export declarations
        "conformance/es6/modules/exportsAndImports4-es6.ts/t3Js.js",
        "conformance/es6/modules/exportsAndImports4-amd.ts/t3Js.js",
        "conformance/es6/modules/exportsAndImports4.ts/t2Js.js",
        "conformance/es6/modules/exportsAndImports4-amd.ts/t2Js.js",
        "compiler/systemModule9Js.js",
        "conformance/es6/modules/exportsAndImports4.ts/t3Js.js",
        "conformance/es6/modules/exportsAndImports4-es6.ts/t2Js.js",
        //differences in module namings
        "compiler/isolatedModulesReExportType.ts/userJs.js",
        "compiler/unusedImports_entireImportDeclaration.ts/bJs.js",
        "conformance/externalModules/typeOnly/chained.ts/bJs.js",
        "compiler/es6ImportDefaultBindingFollowedWithNamedImportWithExport.ts/clientJs.js",
        "compiler/es6ImportDefaultBindingFollowedWithNamedImportDts.ts/clientJs.js",
        "compiler/es6ImportDefaultBindingFollowedWithNamedImportInEs5.ts/es6ImportDefaultBindingFollowedWithNamedImportInEs5_1Js.js",
        "compiler/es6ImportDefaultBindingFollowedWithNamedImport.ts/es6ImportDefaultBindingFollowedWithNamedImport_1Js.js",
        "compiler/es6ExportEqualsInterop.ts/mainJs.js",
        //should be bug in Typescript with non-deleted unnecessary or unused import
        "conformance/internalModules/importDeclarations/importAliasIdentifiersJs.js",
        "conformance/internalModules/importDeclarations/invalidImportAliasIdentifiersJs.js",
        "compiler/duplicateVarAndImport2Js.js",
        "compiler/jsdocInTypeScriptJs.js",
        "compiler/collisionThisExpressionAndAliasInGlobalJs.js",
        "compiler/moduleAliasInterfaceJs.js",
        "conformance/externalModules/commonJSImportNotAsPrimaryExpression.ts/foo_1Js.js",
        "conformance/externalModules/amdImportNotAsPrimaryExpression.ts/foo_1Js.js",
        "compiler/aliasBugJs.js",
        //TS1380: import type only. TS1361:
        "conformance/externalModules/typeOnly/exportDefault.ts/gJs.js",
        "conformance/externalModules/typeOnly/importEquals3.ts/bJs.js",
        "conformance/externalModules/typeOnly/importClause_default.ts/bJs.js",
        "conformance/externalModules/typeOnly/filterNamespace_import.ts/aJs.js",
        "conformance/externalModules/typeOnly/importEquals1.ts/gJs.js",
        //TS2309: An export assignment cannot be used in a module with other exported elements.
        "conformance/parser/ecmascript5/ExportAssignments/parserExportAssignment8Js.js",
        "compiler/ExportAssignment7Js.js",
        "compiler/ExportAssignment8Js.js",
        "compiler/es6ExportEqualsJs.js",
        "compiler/es5ExportEqualsJs.js",
        "compiler/exportAssignmentWithExportsJs.js",
        "conformance/parser/ecmascript5/ExportAssignments/parserExportAssignment7Js.js",
        //TODO: check this! there shouldn't be reference, could be tricky in realization
        "conformance/enums/enumMergingJs.js",
        "compiler/mergedDeclarations4Js.js",
        "compiler/emitMemberAccessExpression.ts/emitMemberAccessExpression_file2Js.js",
        //TS1147: Import declarations in a namespace cannot reference a module.
        "projects/privacyCheck-InsideModule/testJs.js",
        "projects/privacyCheck-InsideModule/testGloJs.js",
        "projects/privacyCheck-ImportInParent/testJs.js",
        "projects/NestedLocalModule-WithRecursiveTypecheck/test1Js.js",
        "compiler/importInsideModule.ts/importInsideModule_file2Js.js",
        "projects/ext-int-ext/internal2Js.js",
        "projects/NestedLocalModule-WithRecursiveTypecheck/test2Js.js",
        //TS2440: Import declaration conflicts with local declaration of '{0}'.
        "compiler/importedEnumMemberMergedWithExportedAliasIsError.ts/aliasJs.js",
        "compiler/namespaceMergedWithImportAliasNoCrash.ts/file2Js.js",
        //TS2323:
        "compiler/declarationFileNoCrashOnExtraExportModifier.ts/inputJs.js",
        //TS1005:
        "compiler/accessorWithoutBody1Js.js",
        "compiler/accessorWithoutBody2Js.js",
        "compiler/abstractPropertyNegativeJs.js",
        //TS1092,TS1093
        "conformance/parser/ecmascript5/ConstructorDeclarations/parserConstructorDeclaration10Js.js",
        "conformance/parser/ecmascript5/ConstructorDeclarations/parserConstructorDeclaration9Js.js",
        //TS1211:
        "compiler/exportClassWithoutNameJs.js",
        //TS1319
        "compiler/exportDefaultFunctionInNamespaceJs.js",
        "compiler/exportDefaultClassInNamespaceJs.js",
        "conformance/parser/ecmascript5/ExportAssignments/parserExportAssignment9Js.js",
        //unterminated nextline chars
        "compiler/fileWithNextLine2Js.js",
        "compiler/fileWithNextLine3Js.js",
        "compiler/sourceMap-LineBreaksJs.js",
        //differences in computed properties transformation
        "conformance/es6/Symbols/symbolProperty7Js.js",
        "compiler/decoratorsOnComputedPropertiesJs.js",
        "conformance/parser/ecmascript6/ComputedPropertyNames/parserComputedPropertyName28Js.js",
        "conformance/externalModules/typeOnly/computedPropertyName.ts/componentJs.js",
        "compiler/variableDeclarationDeclarationEmitUniqueSymbolPartialStatementJs.js",
        //TS2332
        "compiler/this_inside-enum-should-not-be-allowedJs.js",
        //TODO: non-merged declarations
        "compiler/enumGenericTypeClashJs.js",
        "compiler/constEnumErrorsJs.js",
        "compiler/augmentedTypesClassJs.js",
        "compiler/augmentedTypesClass2Js.js",
        "compiler/augmentedTypesFunctionJs.js",
        //TS2334:
        "compiler/augmentedTypesModules2Js.js",
        "compiler/augmentedTypesModulesJs.js",
        "conformance/internalModules/DeclarationMerging/ModuleAndFunctionWithSameNameAndCommonRoot.ts/simpleJs.js",
        //TODO: numeric separators
        "conformance/salsa/typeFromPropertyAssignment29Js.js",
        "conformance/parser/ecmascriptnext/numericSeparators/parser.numericSeparators.hexJs.js",
        "conformance/parser/ecmascriptnext/numericSeparators/parser.numericSeparators.binaryJs.js",
        "conformance/parser/ecmascriptnext/numericSeparators/parser.numericSeparators.octalJs.js",
        "conformance/salsa/typeFromPropertyAssignment29Js.js",
        "conformance/parser/ecmascriptnext/numericSeparators/parser.numericSeparators.decimalJs.js",
        "compiler/bigIntWithTargetES3Js.js", //actually bigint
        //TODO: trailing slashes in imports?
        "compiler/importWithTrailingSlash.ts/a/testJs.js",
        "compiler/importWithTrailingSlash.ts/a/b/testJs.js",
        "compiler/exportStarNotElided.ts/data1Js.js",
        //TS1315:
        "conformance/externalModules/umd-errors.ts/err5Js.js",
        //strange case with quoted constructors
        "conformance/classes/constructorDeclarations/quotedConstructorsJs.js",
        //TODO: empty object/array bindging patterns
        "compiler/exportEmptyObjectBindingPatternJs.js",
        "compiler/exportEmptyArrayBindingPatternJs.js",
        //TODO: may be bug with wrong import
        "compiler/exportImportCanSubstituteConstEnumForValueJs.js",
        //unneccessary import chain:  difficult to solve
        "compiler/importedAliasesInTypePositions.ts/file2Js.js",
        //TODO: unicode in enums
        "compiler/enumWithUnicodeEscape1Js.js",
        //TS1358:
        "conformance/expressions/optionalChaining/taggedTemplateChain/taggedTemplateChainJs.js",
        //TODO: decorator references??
        "compiler/decoratorReferencesJs.js",
        //just shadow import
        "compiler/noCrashOnImportShadowing.ts/aJs.js",
        //strange case
        "compiler/parseGenericArrowRatherThanLeftShiftJs.js",
        "compiler/reExportUndefined1.ts/aJs.js",
        //Object.defineProperty instead of exports
        "conformance/es6/modules/exportsAndImports3-amd.ts/t1Js.js",
        "conformance/es6/modules/exportsAndImports3-es6.ts/t1Js.js",
        "conformance/es6/modules/exportsAndImports3.ts/t1Js.js",
    ];