#!/usr/bin/env bash
node diff.js typescript_tests/tests/cases tests-before
#in argument should be path to typescript tests cases, generated by prepare-tests
node generator.js typescript_tests/tests/cases -d
node diff.js typescript_tests/tests/cases tests-after
#compare-files now outputs html diffs in Chrome Browser, if there are many right changes it could really "eat" memory
node compare-files.js