#!/usr/bin/env bash
#in argument should be path to typescript tests cases
node prepare-tests.js tests/cases
#in argument should be path to typescript tests cases, generated by prepare-tests
node generator.js typescript_tests/tests/cases -d
#in argument should be path to typescript tests cases, generated by prepare-tests
node generate-js-transpile-ts.js typescript_tests/tests/cases -d